onerror { quit -f -code 1 }
vlog -work work \
    +incdir+tb/global \
    +incdir+tb/env \
    +incdir+tb/agents/mdio \
    +incdir+tb/sequences/mdio_seq \
    tb/global/eth_glob_pkg.sv \
    tb/interfaces/*.sv \
    tb/config/eth_config_pkg.sv \
    tb/seq_items/reset/reset_seq_item_pkg.sv \
    tb/seq_items/mii_tx/mii_tx_seq_item_pkg.sv \
    tb/seq_items/wb_m/wb_m_seq_item_pkg.sv \
    tb/seq_items/wb_s/wb_s_seq_item_pkg.sv \
    tb/seq_items/mii_rx/mii_rx_seq_item_pkg.sv \
    tb/seq_items/mdio/mdio_seq_item_pkg.sv \
    tb/ral/eth_ral_pkg.sv \
    tb/agents/reset/reset_agent_pkg.sv \
    tb/agents/wb_m/wb_m_agent_pkg.sv \
    tb/agents/wb_s/wb_s_agent_pkg.sv \
    tb/agents/mii_tx/mii_tx_agent_pkg.sv \
    tb/agents/mii_rx/mii_rx_agent_pkg.sv \
    tb/agents/mdio/mdio_agent_pkg.sv \
    tb/sequences/reset_seq/reset_seq_pkg.sv \
    tb/sequences/wb_m_seq/wb_m_seq_pkg.sv \
    tb/sequences/wb_s_seq/wb_s_seq_pkg.sv \
    tb/sequences/mii_tx_seq/mii_tx_seq_pkg.sv \
    tb/sequences/mdio_seq/mdio_seq_pkg.sv \
    tb/virtual_seq_sqr/eth_v_seq_sqr_pkg.sv \
    tb/scoreboards/eth_tx_scoreboard/eth_tx_scoreboard_pkg.sv \
    tb/scoreboards/eth_rx_scoreboard/eth_rx_scoreboard_pkg.sv \
    tb/scoreboards/eth_mdio_scoreboard/eth_mdio_scoreboard_pkg.sv \
    tb/coverage/eth_cov_pkg.sv \
    tb/env/eth_env_pkg.sv \
    tb/tests/eth_tests_tx/eth_test_tx_pkg.sv \
    tb/tests/eth_tests_reg/eth_test_reg_pkg.sv \
    tb/tests/eth_tests_mdio/eth_test_mdio_pkg.sv \
    rtl/*.v \
    tb/top/eth_tb.sv \
    +cover -covercells